return {
    tempo=600000,
    notes={
        {
            note=84,
            time=2.4
        },
        {
            note=84,
            time=3.0
        },
        {
            note=84,
            time=3.6
        },
        {
            note=84,
            time=4.2
        },
        {
            note=86,
            time=4.8
        },
        {
            note=86,
            time=5.4
        },
        {
            note=86,
            time=6.0
        },
        {
            note=86,
            time=6.6
        },
        {
            note=88,
            time=7.2
        },
        {
            note=88,
            time=7.8
        },
        {
            note=88,
            time=8.4
        },
        {
            note=88,
            time=9.0
        },
        {
            note=89,
            time=9.6
        },
        {
            note=89,
            time=10.2
        },
        {
            note=89,
            time=10.8
        },
        {
            note=89,
            time=11.4
        },
        {
            note=91,
            time=12.0
        },
        {
            note=88,
            time=12.6
        },
        {
            note=84,
            time=13.2
        },
        {
            note=88,
            time=13.8
        },
        {
            note=89,
            time=14.4
        },
        {
            note=88,
            time=15.0
        },
        {
            note=86,
            time=15.6
        },
        {
            note=88,
            time=16.2
        },
        {
            note=84,
            time=16.8
        }
    }
}
