return {
    tempo=722892,
    notes={
        {
            note=84,
            time=8.67
        },
        {
            note=84,
            time=10.3
        },
        {
            note=86,
            time=10.48
        },
        {
            note=84,
            time=10.66
        },
        {
            note=91,
            time=10.84
        },
        {
            note=89,
            time=11.2
        },
        {
            note=88,
            time=11.39
        },
        {
            note=89,
            time=11.57
        },
        {
            note=91,
            time=13.01
        },
        {
            note=91,
            time=13.22
        },
        {
            note=88,
            time=13.55
        },
        {
            note=86,
            time=13.92
        },
        {
            note=84,
            time=14.1
        },
        {
            note=84,
            time=14.46
        },
        {
            note=84,
            time=15.36
        },
        {
            note=86,
            time=15.54
        },
        {
            note=88,
            time=15.72
        },
        {
            note=89,
            time=15.9
        },
        {
            note=88,
            time=16.27
        },
        {
            note=86,
            time=16.81
        },
        {
            note=88,
            time=16.99
        },
        {
            note=89,
            time=17.17
        },
        {
            note=91,
            time=17.35
        },
        {
            note=91,
            time=17.71
        },
        {
            note=91,
            time=18.07
        },
        {
            note=91,
            time=18.61
        },
        {
            note=89,
            time=18.8
        },
        {
            note=88,
            time=18.98
        },
        {
            note=89,
            time=19.16
        },
        {
            note=91,
            time=19.34
        },
        {
            note=89,
            time=19.52
        },
        {
            note=88,
            time=19.7
        },
        {
            note=86,
            time=19.88
        },
        {
            note=88,
            time=20.06
        },
        {
            note=84,
            time=20.24
        },
        {
            note=84,
            time=20.6
        },
        {
            note=91,
            time=20.96
        },
        {
            note=89,
            time=21.87
        },
        {
            note=91,
            time=22.41
        },
        {
            note=91,
            time=22.59
        },
        {
            note=91,
            time=22.77
        },
        {
            note=91,
            time=22.95
        },
        {
            note=84,
            time=23.31
        },
        {
            note=86,
            time=23.49
        },
        {
            note=88,
            time=23.67
        },
        {
            note=89,
            time=23.86
        },
        {
            note=88,
            time=24.04
        },
        {
            note=86,
            time=24.22
        },
        {
            note=88,
            time=24.4
        },
        {
            note=88,
            time=24.58
        },
        {
            note=91,
            time=24.76
        },
        {
            note=89,
            time=24.94
        },
        {
            note=89,
            time=25.15
        },
        {
            note=86,
            time=25.3
        },
        {
            note=88,
            time=25.48
        },
        {
            note=88,
            time=25.68
        },
        {
            note=84,
            time=25.84
        },
        {
            note=84,
            time=26.02
        },
        {
            note=84,
            time=27.11
        },
        {
            note=84,
            time=27.47
        },
        {
            note=91,
            time=28.92
        },
        {
            note=89,
            time=29.1
        },
        {
            note=88,
            time=29.46
        },
        {
            note=88,
            time=29.82
        },
        {
            note=91,
            time=30.0
        },
        {
            note=91,
            time=30.54
        },
        {
            note=91,
            time=30.75
        },
        {
            note=88,
            time=30.9
        },
        {
            note=86,
            time=31.08
        },
        {
            note=88,
            time=31.27
        },
        {
            note=89,
            time=31.45
        },
        {
            note=89,
            time=31.68
        },
        {
            note=84,
            time=31.81
        },
        {
            note=84,
            time=32.53
        },
        {
            note=88,
            time=33.25
        },
        {
            note=88,
            time=33.44
        },
        {
            note=86,
            time=33.8
        },
        {
            note=91,
            time=34.16
        },
        {
            note=89,
            time=34.7
        },
        {
            note=89,
            time=35.42
        },
        {
            note=89,
            time=35.6
        },
        {
            note=86,
            time=35.78
        },
        {
            note=86,
            time=35.96
        },
        {
            note=84,
            time=36.33
        },
        {
            note=84,
            time=36.69
        },
        {
            note=84,
            time=36.87
        },
        {
            note=86,
            time=37.05
        },
        {
            note=84,
            time=37.23
        },
        {
            note=84,
            time=37.59
        },
        {
            note=86,
            time=39.04
        },
        {
            note=86,
            time=39.22
        },
        {
            note=86,
            time=39.4
        },
        {
            note=86,
            time=39.58
        },
        {
            note=88,
            time=39.76
        },
        {
            note=88,
            time=39.94
        },
        {
            note=88,
            time=40.12
        },
        {
            note=88,
            time=40.3
        },
        {
            note=89,
            time=40.48
        },
        {
            note=91,
            time=41.39
        },
        {
            note=91,
            time=41.61
        },
        {
            note=89,
            time=41.75
        },
        {
            note=89,
            time=41.93
        },
        {
            note=89,
            time=42.12
        },
        {
            note=86,
            time=42.29
        },
        {
            note=89,
            time=42.47
        },
        {
            note=89,
            time=42.67
        },
        {
            note=86,
            time=42.83
        },
        {
            note=86,
            time=43.02
        },
        {
            note=86,
            time=43.19
        }
    }
}
