return {
    tempo=750000,
    notes={
        {
            note=84,
            time=9.0
        },
        {
            note=91,
            time=9.75
        },
        {
            note=89,
            time=10.5
        },
        {
            note=88,
            time=10.88
        },
        {
            note=89,
            time=11.62
        },
        {
            note=88,
            time=12.38
        },
        {
            note=86,
            time=13.12
        },
        {
            note=84,
            time=13.5
        },
        {
            note=86,
            time=13.69
        },
        {
            note=84,
            time=13.88
        },
        {
            note=86,
            time=14.06
        },
        {
            note=84,
            time=14.25
        },
        {
            note=84,
            time=14.62
        },
        {
            note=84,
            time=15.0
        },
        {
            note=91,
            time=15.75
        },
        {
            note=89,
            time=16.5
        },
        {
            note=88,
            time=16.88
        },
        {
            note=89,
            time=17.62
        },
        {
            note=88,
            time=18.38
        },
        {
            note=86,
            time=19.12
        },
        {
            note=84,
            time=19.5
        },
        {
            note=86,
            time=19.69
        },
        {
            note=84,
            time=19.88
        },
        {
            note=86,
            time=20.06
        },
        {
            note=84,
            time=20.25
        },
        {
            note=84,
            time=20.62
        },
        {
            note=84,
            time=21.0
        },
        {
            note=91,
            time=21.75
        },
        {
            note=89,
            time=22.5
        },
        {
            note=88,
            time=22.88
        },
        {
            note=89,
            time=23.62
        },
        {
            note=88,
            time=24.38
        },
        {
            note=86,
            time=25.12
        },
        {
            note=84,
            time=25.5
        },
        {
            note=86,
            time=25.69
        },
        {
            note=84,
            time=25.88
        },
        {
            note=86,
            time=26.06
        },
        {
            note=84,
            time=26.25
        },
        {
            note=84,
            time=26.62
        },
        {
            note=84,
            time=27.0
        },
        {
            note=86,
            time=30.0
        },
        {
            note=88,
            time=31.5
        },
        {
            note=88,
            time=31.69
        },
        {
            note=88,
            time=32.06
        },
        {
            note=86,
            time=32.44
        },
        {
            note=84,
            time=33.0
        },
        {
            note=91,
            time=33.75
        },
        {
            note=89,
            time=34.5
        },
        {
            note=88,
            time=34.88
        },
        {
            note=89,
            time=35.62
        },
        {
            note=88,
            time=36.38
        },
        {
            note=86,
            time=37.12
        },
        {
            note=84,
            time=37.5
        },
        {
            note=86,
            time=37.69
        },
        {
            note=84,
            time=37.88
        },
        {
            note=86,
            time=38.06
        },
        {
            note=84,
            time=38.25
        },
        {
            note=84,
            time=38.62
        },
        {
            note=84,
            time=39.0
        },
        {
            note=91,
            time=39.75
        },
        {
            note=89,
            time=40.5
        },
        {
            note=88,
            time=40.88
        },
        {
            note=89,
            time=41.62
        },
        {
            note=88,
            time=42.38
        },
        {
            note=86,
            time=43.12
        },
        {
            note=84,
            time=43.5
        },
        {
            note=86,
            time=43.69
        },
        {
            note=84,
            time=43.88
        },
        {
            note=86,
            time=44.06
        },
        {
            note=84,
            time=44.25
        },
        {
            note=84,
            time=44.62
        },
        {
            note=84,
            time=45.0
        },
        {
            note=91,
            time=45.75
        },
        {
            note=89,
            time=46.5
        },
        {
            note=88,
            time=46.88
        },
        {
            note=89,
            time=47.62
        },
        {
            note=88,
            time=48.38
        },
        {
            note=86,
            time=49.12
        },
        {
            note=88,
            time=51.0
        },
        {
            note=89,
            time=54.0
        },
        {
            note=91,
            time=55.5
        },
        {
            note=91,
            time=55.69
        },
        {
            note=91,
            time=56.06
        },
        {
            note=89,
            time=56.44
        }
    }
}
