return {
    tempo=722892,
    notes={
        {
            note=84,
            time=2.89
        },
        {
            note=86,
            time=5.78
        },
        {
            note=84,
            time=8.67
        },
        {
            note=88,
            time=11.57
        },
        {
            note=89,
            time=13.01
        },
        {
            note=84,
            time=14.46
        },
        {
            note=86,
            time=17.35
        },
        {
            note=84,
            time=20.24
        },
        {
            note=88,
            time=23.13
        },
        {
            note=88,
            time=23.31
        },
        {
            note=88,
            time=23.49
        },
        {
            note=88,
            time=23.67
        },
        {
            note=88,
            time=23.86
        },
        {
            note=88,
            time=24.04
        },
        {
            note=88,
            time=24.22
        },
        {
            note=88,
            time=24.4
        },
        {
            note=88,
            time=24.58
        },
        {
            note=89,
            time=24.94
        },
        {
            note=84,
            time=26.02
        },
        {
            note=84,
            time=26.57
        },
        {
            note=84,
            time=26.76
        },
        {
            note=86,
            time=26.94
        },
        {
            note=89,
            time=27.29
        },
        {
            note=88,
            time=27.65
        },
        {
            note=84,
            time=28.92
        },
        {
            note=84,
            time=29.46
        },
        {
            note=86,
            time=29.64
        },
        {
            note=88,
            time=29.82
        },
        {
            note=89,
            time=30.18
        },
        {
            note=91,
            time=30.54
        },
        {
            note=91,
            time=30.9
        },
        {
            note=91,
            time=31.08
        },
        {
            note=89,
            time=31.45
        },
        {
            note=84,
            time=31.81
        },
        {
            note=84,
            time=32.35
        },
        {
            note=86,
            time=32.53
        },
        {
            note=88,
            time=32.71
        },
        {
            note=88,
            time=33.07
        },
        {
            note=86,
            time=33.43
        },
        {
            note=84,
            time=34.7
        },
        {
            note=84,
            time=35.24
        },
        {
            note=86,
            time=35.42
        },
        {
            note=88,
            time=35.6
        },
        {
            note=88,
            time=35.96
        },
        {
            note=86,
            time=36.33
        },
        {
            note=88,
            time=36.87
        },
        {
            note=89,
            time=37.23
        },
        {
            note=86,
            time=37.59
        },
        {
            note=86,
            time=38.13
        },
        {
            note=86,
            time=38.34
        },
        {
            note=88,
            time=38.86
        },
        {
            note=89,
            time=39.22
        },
        {
            note=88,
            time=39.58
        },
        {
            note=88,
            time=39.94
        },
        {
            note=86,
            time=40.12
        },
        {
            note=84,
            time=40.48
        },
        {
            note=84,
            time=41.02
        },
        {
            note=86,
            time=41.2
        },
        {
            note=86,
            time=41.75
        },
        {
            note=86,
            time=42.11
        },
        {
            note=88,
            time=42.47
        },
        {
            note=88,
            time=42.83
        },
        {
            note=86,
            time=43.01
        },
        {
            note=84,
            time=43.37
        },
        {
            note=84,
            time=43.92
        },
        {
            note=86,
            time=44.1
        },
        {
            note=88,
            time=44.64
        },
        {
            note=88,
            time=45.0
        },
        {
            note=89,
            time=45.36
        },
        {
            note=88,
            time=45.72
        },
        {
            note=86,
            time=45.9
        },
        {
            note=86,
            time=46.27
        },
        {
            note=89,
            time=48.07
        },
        {
            note=91,
            time=49.16
        },
        {
            note=86,
            time=52.05
        }
      }
}
