story = {}
story[1] = {"Tuto : Les présentations", 0, 0}
story[2] = {"Bienvenue dans le jeu \"Rock Band: Whispers On Tree !\"", 2, 1}
story[3] = {"C'est guigui qui vous parle !\n Voici les personnages du jeu.", 2, 1}
story[4] = {"Moi c'est djé ! Je joue de la guitatr, de la pétanque et je bois du jaune.", 1, 3}
story[5] = {"Moi c'est Léo, je suis corse, espagnol.", 3, 1}
story[6] = {"Mais je suis né à Paris.", 3, 1}
story[7] = {"Moi c'est Kevin, AKA La pépite et addict au Monster", 4, 1}
story[8] = {"!!!?", 5, 2}
story[9] = {"Bah alors présente toi ?", 2, 1}
story[10] = {"Je m'appelle Gaël !", 5, 1}
story[11] = {"!!!? Mais what !!?", 3, 2}
story[12] = {"Je suis BATTEUR !", 5, 1}
story[13] = {"J'arrive du futur.", 5, 1}
story[14] = {"Trop cool, une touche de modernisme dans notre groupe.", 1, 1}
story[15] = {"Et du coup Guss, qu'est ce qu'on fait ici au juste ?", 4, 1}
story[16] = {"Je m'ennuie en confinement alors j'ai fais ce jeu, ça vous branche ?", 2, 1}
story[17] = {"Ah ouai trop cool !", 1, 3}
story[18] = {"Ne se prononce pas...", 4, 1}
story[19] = {"!!!?", 5, 2}
story[20] = {"Sha tu veux jouer toi ?", 2, 1}
story[21] = {"On peut tricher ou pas ?", 6, 1}
story[22] = {"Non !", 2, 1}
story[23] = {"Bah alors je joue pas, en plus ça à l'air d'être de la merde !", 6, 1}
story[24] = {"Du coup le jeu c'est un peu un Guitar Hero du pauvre.", 2, 1}
story[25] = {"Il faut jouer les notes en rythme avec les touches A Z E R T.", 2, 1}
story[26] = {"On va commencer par un petit exemple ;-)", 2, 1}
story[27] = {"!!!?", 5, 2}
return story
